# Generated by Django 4.2.7 on 2023-11-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymp_id', models.IntegerField(max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('hours', models.IntegerField(max_length=7)),
                ('description', models.TextField()),
                ('ordinal', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deparment', models.CharField(max_length=255)),
                ('ymp_id', models.IntegerField(max_length=8)),
                ('role_name', models.CharField(blank=True, max_length=100)),
                ('role_level', models.IntegerField(max_length=7)),
                ('ordinal', models.ImageField(upload_to='')),
            ],
        ),
    ]
