# Generated by Django 4.2.7 on 2023-11-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='deparment',
            new_name='department',
        ),
    ]
