# Generated by Django 4.2.7 on 2023-11-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ymp_id',
            field=models.CharField(blank=True, default='1243826', editable=False, max_length=6, unique=True),
        ),
    ]
