# Generated by Django 4.2.7 on 2023-11-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_customuser_ymp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourTrackings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymp_id', models.CharField(default=0, max_length=6)),
                ('hours', models.IntegerField()),
                ('work_description', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
