# Generated by Django 4.2.7 on 2023-11-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_deparment_role_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='ordinal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='ordinal',
            field=models.IntegerField(),
        ),
    ]
