# Generated by Django 4.2.7 on 2023-11-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_customuser_ymp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ymp_id',
            field=models.CharField(default='1476938', max_length=6, unique=True),
        ),
    ]
