# Generated by Django 4.2.7 on 2023-11-18 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_hourtrackings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HourTrackings',
            new_name='HourRecord',
        ),
    ]
