# Generated by Django 4.2.7 on 2023-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_customuser_ymp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ymp_id',
            field=models.CharField(default='518280', max_length=6, unique=True),
        ),
    ]
