# Generated by Django 4.2.7 on 2024-01-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_hourtrackings_hourrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourrecord',
            name='next_week_plans',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourrecord',
            name='teamlead_email',
            field=models.EmailField(default=2, max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourrecord',
            name='ymp_id',
            field=models.CharField(default=0, max_length=6, unique=True),
        ),
    ]
