# Generated by Django 4.2.7 on 2024-01-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_hourrecord_next_week_plans_hourrecord_teamlead_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourrecord',
            name='teamlead_email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='hourrecord',
            name='ymp_id',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
