# Generated by Django 4.2.7 on 2024-01-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_hourrecord_teamlead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourrecord',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
