# Generated by Django 4.2.7 on 2024-01-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_hourrecord_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teamlead_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
